apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: artifactory-access
  namespace: ci
spec:
  encryptedData:
    ARTIFACTORY_ENCRYPT: AgBmH7af9Sf7glT+6IdtgO0qiuAPdtqSgWIR4Xt9HHWwRJ6QdLvd/LdjGoHui+11bro2hUalaUjdDljktImowbRJkAC3jAlNvwGVX0RJOHM5kyjMLxAj11Kwwkx1XANwDojZaOyVJ1ds57mnOtTqzLa6Wq5RVYvyyMF6y1PY/Ep6CreTwFbji6FGeyqk8nBCTgy6JyBFMkqmm273SYkKzKN5k9PO3OsUaCenCXx8zZ9ezYNrP7Vded2zxpXcwm2emcYg2Zl1RONRHadX4/w3LcaFnkt6TfT16HiE5g7lKynaR2jWiNIm5fQmHGqA+M2mjGUap2xKSS7AN9aMw/QijMs3IvCrAKJdv8MNInC548AcQ1kDA63G1tm/7oRydtkHgtbrAxgod4PDTISPOi6KvzcejR1J2S4hoC4nLfxvltXoX/MaHuoIBuq8QVjJDOJTMr31Gkkp1n8N2abvh3MjmYD1WNrZgtHN164WD22YB2gVTTTm5qqlgh+kjcGGKodhec53OIQ593oIXnL+JbssGv02qpPg/egSUu770FNCjnJ8fQFYQCN1sH6//e6z5G77Nkz/aB2iZYoJmnKP0/VEDk1ET7nqeT+Zadx8hoMKJLhwfz0sTq6ibr9rynqnMbmikXYY5ytH2efbwemdc89TeNzyxJkJK4m+CIY6onokSrx5s0+Z0QAIRNheQ42eLZwv5BXrh/mcJGujhAvRnQa2hXPeHltxlcZZLM2NHXDQArBDDpoFbwxDNQ==
    ARTIFACTORY_PASSWORD: AgCQvu0+k0u/32SvMzw8TwzSrnELlQjZHr1aSXP+liMnb1KszxLZBNWRt4ACYC2uhLnGfTN8mU9BKvr5pIq/VB4Kf777IIHBLefI6P+nMZ0Db66gRR9HAuFrCx/5F2Rl26bltuLOewWWcbZ7wqvGqIA0Fa4G3QkqmS1Gq+//xzIaACbVeGmagzf4pu3tvUOQmuBUlLEDfx/YXN26Hl/Fh8w1pLuuqb1ARXaMCgqUcyiMEcAIerdpJBhzI52DDM29pV7BA81KjsSokEzdIMVJ7VbMMqO97OurpZGt8loh1yeYTPBmSlcOSB9EbmEwxbUpDsI6G2TxrrEQ1j1kssWRIqJ/I87SLCJVY055tbg+GKaK9dnZBUfKQ+HTJflgv8rdyB9NoXVObVTMx1VFH+azG4kf1BF6JIUj9yQDLwpIA9xsA2QhxxNPJA8F+69nj4lQJkqH1JbHcG3hfcIANnr6Vk2Rr52IKiIoXqla5p9RZVkmWBuru47TacCedRBScK4FwuBR1FHEPWnFsWYNbuz3Ms37aPI8CC/zZ0Cyhe6WcRVkwR7vuPBFskYdZKpKR5oSvwjYkFKYWo7c0dVzpLTUbDjgmFXW3aNwjoRjhzgcujTQ1u02pXR15JAzY0vqHRH3RE9bNwPI1bdZlaKnkHvAtQ+X12Z10GIXWzSZNUNE6AnXGcX5ShB2woalHUI0ySbH7e3rfOV/Sfq9R4d9msgsNJjeG+UM5Q==
    ARTIFACTORY_URL: AgAIfnWeF5iO10wuaGZoNwinzSd629N1pEYFm0pwoKvC371pnpUmR0US73ks8fZm8Zmd5F2EHHygjsN8VUkTORj+RdJM2UxuBHLwNshVRQBqBxUETzptHUc+bZt1kfTx0rLRS/ifiSKhTafLe6Z+xXyaxDDbXAGnZuIoA3nvOH/xlx31Sx3bYrm2GkFnSz8aFf6KrjS+hDQCzLqZ85nqs7sZm6WF/zgorvvXNp5LoZd2nlQJL71DGQn88vBMXSAoLOsFEiaWDjQn0t1rVXUXzeELgkOt9iLj/kIe3rU2HfHsLJ5yI1gjCqlpziLOT7C11pC+XoRA4ntQGdRO0XFENgTJraxXm76Awg18nw1vI8K3i0QHO+gY2hqsX/rWyfAf29oP5idxhBneofKFWlbFx7AqW2F/ax3+/cnU0Mp5H7Nec3SDxyqDYdAERE8bDIbYLkN4i6gkwQczr9f/68+xspaVXqheqR7NJkJNTtu1j9C8q9g0FZu5JrHqqFYFuqtVbpg/gsKo5CpQp+qVjEweSRQLRgQ92T8UFVTT+DwkIdMzaKHoQks0Rr0+OsF9ic8hUuORUU4PrjfRlwesN4wiTkVuIdfZCPe+i/kF9lrimkktLoTkb64JqqcO29VA747TpNqpJvIkl9id2P5ypg+UCCUOp5A2vgvpYH/cDSAKeB+omPmJnR+utOmoNRux2MEDC+c3BFW9qQx0zJRqXm4xWxjS47RZUvAZkA06VkMGlk+MqiuU9b7YxKdYVg==
    ARTIFACTORY_USER: AgAH8kK5rFS/sgTMAybz7eTNALWZsiFsFjFMtel1ITWe8tJYeHaGfrEhzU5jGFDxc1r/g3X0T9mi2DmItRyy6YUIsf0E84RjvJlRt+iuPo/+VkAucP1E5y03hYC3GAbiVNootL2YvQKeVxHbcnQbyw60aF6rQhlRtrfqzfjsbWHXp/niEAJpnlkj9W2gJpQ9ZUey3hx5+7Ywls8NnsC3/sPkLc2JL68PWF2F3e1yAt0yntMp8GqaI2x1f01OLt4i/emGpJudHuYjlxlFt+H82az1txNHXpuv3fD3XT4aIPQ25MUSxg9Vrmg9uJqFRylKVCCC475Gi87D6iU5T/+7Ezp9q9AtDWo3Jd+7jrWoywQqOvx9acUFx2ZeRMDbYPBeHmvgJ8WgAcSeDjPWbk1SVdX+j+GrJb97F+QscUlR9qiXujupCJdsiCHCa9V/KMo48GENUoTlCTAO5/MDTdxk8GyTGEZ3YI5mGtjHMJ9qPO56d2CtQvHU6r0gZMuhIfciR7k8jkZsUiBQPcxDiyVsvvpTXmt8DEkPYugmD/k2X0bdK2IzP7zDJJ1ByZi4T53GFGkahrDhVFca/YXVkaIyA38/jbi8VoknWo+uAhjMF5I6EFEiT7FFT39BJoGhXpQl2kVIDFKM1kIzSn/CyQpl2XUSv3imnV2YIAssu9Ep4XowBpO4HDn4/pAp5YyPeF59D1inAOV/eQ==
  template:
    data: null
    metadata:
      creationTimestamp: null
      managedFields:
      - apiVersion: v1
        fieldsType: FieldsV1
        fieldsV1:
          f:data:
            .: {}
            f:ARTIFACTORY_URL: {}
            f:ARTIFACTORY_USER: {}
          f:type: {}
        manager: kubectl
        operation: Update
        time: "2021-11-06T18:59:29Z"
      - apiVersion: v1
        fieldsType: FieldsV1
        fieldsV1:
          f:data:
            f:ARTIFACTORY_ENCRYPT: {}
            f:ARTIFACTORY_PASSWORD: {}
        manager: unknown
        operation: Update
        time: "2021-11-06T19:01:40Z"
      name: artifactory-access
      namespace: ci
    type: Opaque

